services:
  app:
    # environment: なし
    ports:
      - "8000:8000"
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass1234
      - MYSQL_DATABASE=sample
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
  mail:
    environment:
      - TZ=Asia/Tokyo
      - MP_DATABASE=/data/mailpit.db
    ports:
      - "8025:8025"
volumes:
  compose-db-volume:
  compose-mail-volume:
