services:
  app:
    ports:
      - "${APP_HOST_MACHINE_PORT}:8000"
    volumes:
      - type: bind
        source: ./src
        target: /my-work
    build:
      context: ./docker/app
      dockerfile: Dockerfile
  db:
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - TZ=Asia/Tokyo
    ports:
      - "${DB_HOST_MACHINE_PORT}:3306"
    volumes:
      - type: volume
        source: compose-db-volume
        target: /var/lib/mysql
      - type: bind
        source: ./docker/db/init
        target: /docker-entrypoint-initdb.d
    image: mysql:9.1.0
  mail:
    environment:
      - TZ=Asia/Tokyo
      - MP_DATABASE=/data/mailpit.db
    ports:
      - "${MAIL_HOST_MACHINE_PORT}:8025"
    volumes:
      - type: volume
        source: compose-mail-volume
        target: /data
    image: axllent/mailpit:v1.21.5
volumes:
  compose-db-volume:
  compose-mail-volume:
